title: Pratik Thanki
logo: /assets/pratik.jpg
description: "I'm a software engineer and an nfl fan. I also write occasionally."
blank_title: true
show_downloads: false
google_analytics: UA-118874438-1
theme: jekyll-theme-minimal
color-scheme: auto
favicon: true

markdown: kramdown
kramdown:
    math_engine: katex

navigation:
- title: about
  path: /
- title: posts
  path: /posts

social:
- title: fourthdown api
  url: https://fourthdown.azurewebsites.net/
  icon: fa-solid fa-football
- title: twitter
  url: https://twitter.com/pratik_thanki
  icon: fa-brands fa-twitter
- title: github
  url: https://github.com/pratikthanki
  icon: fa-brands fa-github
- title: linkedin
  url: https://www.linkedin.com/in/-pratikthanki
  icon: fa-brands fa-linkedin
