title: Pratik Thanki
logo: /assets/pratik.jpg
description: "I'm a software engineer and an nfl fan. I also write occasionally."
blank_title: true
show_downloads: false
google_analytics: UA-118874438-1
theme: jekyll-theme-minimal
color-scheme: auto
favicon: true

markdown: kramdown
kramdown:
    math_engine: katex

navigation:
- title: about
  path: /
- title: posts
  path: /posts

social:
- title: twitter
  url: https://twitter.com
  handle: pratik_thanki
  icon: fa fa-twitter
- title: github
  url: https://github.com
  handle: pratikthanki
  icon: fa fa-github
- title: linkedin
  url: https://www.linkedin.com/in
  handle: -pratikthanki
  icon: fa fa-linkedin
- title: email
  url: "mailto:pratikthanki1@gmail.com?subject=Hello!&body=Hi,\nthis is only a test!"
  handle: ""
  icon: fa fa-envelope
