title: Pratik Thanki
logo: /assets/pratik.jpg
description: "I'm a software engineer and an nfl fan. I also write occasionally."
blank_title: true
show_downloads: false
google_analytics: UA-118874438-1
theme: jekyll-theme-minimal
color-scheme: auto
favicon: true

navigation:
- title: about
  path: /
- title: posts
  path: /posts

social:
- title: twitter
  url: https://twitter.com
  handle: pratik_thanki
  icon: fa fa-twitter
- title: gitHub
  url: https://github.com
  handle: pratikthanki
  icon: fa fa-github
- title: linkedIn
  url: https://www.linkedin.com/in
  handle: -pratikthanki
  icon: fa fa-linkedin
  